# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push functionapphttp docker image to Azure Docker Container Registry
      inputs:
        command: buildAndPush
        buildContext: '$(Build.SourcesDirectory)'
        dockerfile: '$(Build.SourcesDirectory)/FunctionApp.HTTP/Dockerfile'
        containerRegistry: 'klassanovdemoregistry'
        repository: 'functionapphttp'        
        tags: |
          $(tag)

    - task: AzureFunctionAppContainer@1
      inputs:
        azureSubscription: 'Azure subscription 1(ff7c8f10-fc27-46db-b76d-2eb797719bd4)'
        appName: 'klassanov-func-container-test'
        imageName: 'klassanovdemoregistry.azurecr.io/functionapphttp:$(tag)'
        appSettings: '-DOCKER_REGISTRY_SERVER_URL $(registryServerUrl) -DOCKER_REGISTRY_SERVER_USERNAME $(registryUsername) -DOCKER_REGISTRY_SERVER_PASSWORD $(registryPassword)'
    

    
    


